const projectContributors = {
    "projects/huge-firey":
        [
            "Reviksedy",
            "BlueStevie64",
            "Nythic",
            "Matheuspixel",
            "akaSandwich",
            "AiryAiryAiry",
            "Fifi",
            "AnalyticalTomato",
            "Simurated",
            "Frenkizaba1",
            "Awsomazing_neil",
            "theonlylizard",
            "PizzaGuy25_a",
            "Sam_Studios",
            "clampity",
            "Fananan",
            "cometztarz",
            "b100rulez",
            "justhanniehere",
            "brightcarp",
            "FernieLeaflen",
            "Legitbeatle",
            "995qa",
            "Amireal71",
            "One (InvisibleThe2nd)",
            "soapdoggie",
            "parfaitheart",
            "SonicFan510",
            "fbghjopy",
            "CoffiCreame",
            "floppedtacos",
            "Billbillson",
            "MagikalTwinkle",
            "JMReg0811",
            "MrPoker",
            "PinkPouDuck",
            "NuggetGgamer",
            "APersonThatIsMe",
            "coolbear11",
            "BLUSPRX",
            "KaiDaJai",
            "Reid",
            "Ajibounce",
            "L0v33rx",
            "Ender",
            "zushyart",
            "polinaa_malin"
        ],
    "projects/tpot-banner":
        [
            "Reviksedy",
            "AnalyticalTomato",
            "One (InvisibleThe2nd)",
            "EpicDemo",
            "L0v33rx",
            "BlueStevie64",
            "AnthonyDaBest",
            "MagikalTwinkle",
            "Frenkizaba1",
            "APersonThatIsMe",
            "PrimeNavigator",
            "zushyart",
            "akaSandwich",
            "Real Pillow BFDI",
            "Papery_",
            "FurryCatto",
            "PizzaGuy25_a",
            "-Tsunami-",
            "SeQuaLL",
            "cometztarz",
            "slimeman",
            "b100rulez",
            "Fifi",
            "BookFan510",
            "Happyguy",
            "polinaa_malin",
            "Charkis",
            "marker the red"
        ],
    "projects/bfdi-poster":
        [
            "1magr3ml1n",
            "10thdoctorwhooves",
            "13_ASDF",
            "67x8",
            "A single dot",
            "Acidy",
            "Aislynn",
            "akaSandwich",
            "AleGX26",
            "Alexcoberti",
            "Am i real?",
            "Amireal71",
            "AnalyticalTomato",
            "AngryHat",
            "AnIdiotBasically",
            "AnonyAndrogy",
            "AnthonyDaBest",
            "APersonThatIsMe",
            "ArKo",
            "Aster",
            "Audrey",
            "Averygood1",
            "B100rulez",
            "bellecipherwaifu",
            "BetterSharker",
            "Billbillson",
            "BlueStevie64",
            "Blusprx",
            "Bobpixels",
            "Bobscool",
            "BookFan510",
            "BorboStuff15",
            "Bowlboy222",
            "BPlushYT",
            "chance",
            "Charkis",
            "Cherry",
            "Chorus",
            "Ckarkis",
            "Clampity",
            "Clean Board",
            "cometztarz",
            "coolreinbeerll",
            "crakdtheglass",
            "Curly Pillow",
            "d7zzz.",
            "Dabokbubble",
            "Detetiveram",
            "Dextronium",
            "DigiDigiMonMon",
            "Dizcordian",
            "Doppy",
            "DucktheFunny",
            "Emersmash",
            "Enrique_20384",
            "EpicDemo",
            "EX :)",
            "Fifi",
            "FireafyFan",
            "Fishy!!",
            "Flamaninaniningo",
            "Floppedtacos",
            "Frenkizaba1",
            "Frootloop_Dust",
            "FunnyComb",
            "FurryCatto",
            "FuzzBug!!",
            "Gabo Metal",
            "GirlCake55",
            "Gmøde",
            "Gort",
            "Grumgrum",
            "HappyFox",
            "HarshShorts",
            "HeresBrazilBall",
            "HitchHikerOSC",
            "HorkGlorped",
            "Huckleberreiz",
            "IAMPROCRASTINATE",
            "InkDrake on W",
            "Ireland2.0",
            "iSH",
            "JackCraftPlays",
            "Jellyfishofficial",
            "JMReg0811",
            "K4rm442",
            "KaiDaJai",
            "karrito٩( ᐛ )و",
            "KatieTheObjectQueen",
            "kattpieouuhh",
            "KayRay",
            "KindShamsشمس",
            "Kit",
            "KiteFlyer",
            "L0v33rx",
            "Legitbeatle",
            "LiamLettuceLad",
            "Lizzythebard324",
            "Lopolopta",
            "Loser#1fan",
            "M1SS1NG T3XTUR3S",
            "MagikalTwinkle",
            "Maple_054",
            "Marker The Green",
            "Matheuspixel",
            "MildShirt",
            "Misha (AiryAiryAiry)",
            "Misticalgoat",
            "Mr Diamond",
            "MrMexicano",
            "MrShoppingBag",
            "Mr.e",
            "Muha",
            "MurderDronesFan",
            "Nekovo",
            "Notro",
            "Nythic",
            "One (InvisibleThe2nd)",
            "Oscar lliance",
            "Ourple",
            "Pancheese",
            "Papery_",
            "Parfaitheart",
            "Pave",
            "Pavetheloser",
            "PeanutBuny27",
            "Pekooda",
            "Peter",
            "PizzaGuy25_a",
            "polinaa_malin",
            "PrimeNavegator",
            "PrimeShirt",
            "Promicha1234",
            "Random Guy",
            "Real Pillow BFDI",
            "Real_CartmanOSC",
            "redshift",
            "RedSketch",
            "Reviksedy",
            "s9",
            "Sabu",
            "sccew",
            "SeQuaLL",
            "ShockRox",
            "Skribbz",
            "SkyTheDragon",
            "Snail :)",
            "SoupFloof",
            "Speedy",
            "Sphis",
            "Stamp056",
            "Staticfiction",
            "StormyClock",
            "StormyDustpan",
            "Strawberrypie3167",
            "StrongCable",
            "TAC2025",
            "Tenifferball",
            "Thani0r",
            "Thehappyguy",
            "TNATPT",
            "TunaBear",
            "Two",
            "Two (keviningot72_56444)",
            "TWOFOUR24",
            "UFO",
            "UrbanMop",
            "Usagi",
            "Vinny",
            "Wenbow",
            "WOOX",
            "WWWWWWWWWWWWWWWW",
            "XTRa",
            "yell0wstarbvrst",
            "yoshikid8",
            "Yoylelemonade",
            "zincium",
            "Zoedesert",
            "zushyart",
            "-Tsunami-",
            "Ладно"
        ],
    "projects/huge-lightbulb":
        [
            "N/A"
        ]
};

function populateProjectContributors(container) {
    const pageId = container.closest('.project-page').id;
    const names = projectContributors[pageId] || [];

    const scrollContainer = container.querySelector('.project-page-contributors-scroll');
    const template = scrollContainer.querySelector('.project-page-contributor');

    scrollContainer.querySelectorAll('.project-page-contributor:not([style*="display: none"])').forEach(el => el.remove());

    const shuffled = [...names].sort(() => Math.random() - 0.5);

    shuffled.forEach(name => {
        const clone = template.cloneNode(true);
        clone.style.display = 'flex';
        clone.querySelector('.contributor-name').textContent = name;
        scrollContainer.appendChild(clone);
    });
}

document.querySelectorAll('.project-page-contributors-container').forEach(container => {
    populateProjectContributors(container);
});
